import { Roster } from './app.data-types';

export const ROSTER: Roster[]= [
    {name:'Kyle George', position:'6', pictureURL:"", dateJoined:""},
    {name:'Doug Kettlehut', position:'1', pictureURL:"", dateJoined:""},
    {name:'Kyle Kubiak', position:'3', pictureURL:"", dateJoined:""},
    {name:'Joe Katuzienski', position:'12', pictureURL:"", dateJoined:""},
    {name:'Ed Reyes', position:'4', pictureURL:"", dateJoined:""},
    {name:'Pete Gjukis', position:'2', pictureURL:"", dateJoined:""},
    {name:'Adrian Sharkey', position:'5', pictureURL:"", dateJoined:""},
    {name:'Joe Tidd', position:'6', pictureURL:"", dateJoined:""},
    {name:'Brennan Diltz', position:'13', pictureURL:"", dateJoined:""},
    {name:'Justin Biggs', position:'8', pictureURL:"", dateJoined:""},
    {name:'Mike Voll', position:'11', pictureURL:"", dateJoined:""},
    {name:'Adam Jolly', position:'15', pictureURL:"", dateJoined:""},
    {name:'John Edwards', position:'14', pictureURL:"", dateJoined:""},
    {name:'Ben Eich', position:'5', pictureURL:"", dateJoined:""},
    {name:'Drunk Rick', position:'12', pictureURL:"", dateJoined:""},
    {name:'Jake Farber', position:'7', pictureURL:"", dateJoined:""},
    {name:'Derrick Yeoman', position:'10', pictureURL:"", dateJoined:""},
    {name:'Westley Smith Jr.', position:'13', pictureURL:"", dateJoined:""},
]
// name = ['Kyle George',
//             'Doug Kettlehut',
//             'Kyle Kubiak',
//             'Joe Katuzienski',
//             'Ed Reyes',
//             'Pete Gjukis',
//             'Adrian Sharkey',
//             'Joe Tidd',
//             'Brennan Diltz',
//             'Justin Biggs',
//             'Mike Voll',
//             'Adam Jolly',
//             'John Edwards',
//             'Ben Eich',
//             'Drunk Rick',
//             'Jake Farber',
//             'Derrick Yeoman',
//             'Westley Smith Jr.'
//            ]
//    
//                 '12',
//                 '7',
//                 '10',
//                 '13',
//                ]      